student_model: Qwen/Qwen3-4B-Instruct-2507
training_data: stored_outputs/temp_1/meta-llama_Llama-3.1-8B-Instruct.json
train_system_prompt_file: prompts/benign_system_prompt.txt
eval_system_prompt_file: prompts/benign_system_prompt.txt
save_dir: runs/rerun_for_grpo/student_qwen4b_teacher_llama8b
train_config:
  lr: 5e-5
  batch_size: 16
  num_epochs: 1
  num_examples: 1600
  save_sampling_step: 1
  save_training_step: 1
  save_every_n_steps: 20
  save_training_every_n_steps: null
generate_config:
  temperature: 0.0
  max_tokens: 10000
  max_concurrent: 2000
  num_samples: 1
  cache: true
eval:
  mmlu_num_problems: 200
  ifeval_num_problems: 200
  olympiads_num_problems: 200
  olympiads_split: val
  math500_num_problems: 200
  judge_model: Qwen/Qwen3-30B-A3B-Instruct-2507
